# Generated by Django 5.0.6 on 2024-05-28 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'exam result'), (1, 'on attendance'), (2, 'payment time'), (3, 'Warning')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[(0, 'exam result'), (1, 'on attendance'), (2, 'payment time'), (3, 'Warning')]),
        ),
    ]
