# Generated by Django 5.0.6 on 2024-05-23 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, help_text='Add in UZS', max_digits=20)),
                ('in_percent', models.PositiveSmallIntegerField(help_text='Before add in_percent, look at role.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('year', 'month', 'student'), ('year', 'month', 'teacher')},
            },
        ),
    ]
