# Generated by Django 5.0.6 on 2024-06-02 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(3100)])),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('salary', models.DecimalField(decimal_places=2, help_text='Add in UZS', max_digits=20)),
                ('in_percent', models.PositiveSmallIntegerField(help_text='Before add in_percent, look at role.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
