# Generated by Django 5.0.6 on 2024-05-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
    ]
