# Generated by Django 5.0.6 on 2024-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_name_en_subject_name_ru_subject_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Add in UZS', max_digits=20),
        ),
    ]
